name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        bun-version: [1.2.3]
        node-version: [22.14]
        pnpm-version: [9.12.3]

    name: 🧪 CI Abi on Node@${{ matrix.node-version }} with PNPM@${{ matrix.pnpm-version }} under ${{ matrix.operating-system }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🎉 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🎉 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: ✨ Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: ⚡️ Install dependencies
        run: pnpm install -r

      - name: 📂 Upload node_modules directory
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: packages/abi.js/node_modules

      - name: ✅ Check code style
        run: pnpm check

      - name: 📦 Build the website
        run: pnpm build

      - name: 📂 Upload Deno distribution files
        uses: actions/upload-artifact@v4
        with:
          name: deno_dist
          path: packages/abi.js/dist/deno
